spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:aula_virtual}?useSSL=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

logging:
  level:
    com.unslg.aulavirtual: INFO
    org.springframework: WARN
    org.hibernate: WARN
  file:
    name: logs/aula-virtual.log

server:
  port: ${PORT:8080}
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-in-ms: 43200000
  
  file:
    upload-dir: ${FILE_UPLOAD_DIR:/var/uploads}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
