spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aula_virtual_dev?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  
  mail:
    host: localhost
    port: 1025

logging:
  level:
    com.unslg.aulavirtual: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: 8080

app:
  jwt:
    secret: devSecretKeyForDevelopment
    expiration-in-ms: 86400000
  
  file:
    upload-dir: uploads-dev
